import type { Content } from '@/types/content';

export const MOCK_CONTENTS: Content[] = [
    {
        id: 'c1',
        title: 'Post de Lançamento do Produto',
        description: 'Apresentação visual do novo produto com carrossel de features principais.',
        type: 'post',
        status: 'approved',
        scheduledAt: '2026-03-11T14:00:00',
        hashtags: ['#lançamento', '#produto', '#novidade'],
        mediaUrls: [],
        accountId: 'a1',
        collectionIds: [],
        order: 0,
        createdAt: '2026-03-09T00:00:00',
        updatedAt: '2026-03-09T00:00:00',
    },
    {
        id: 'c2',
        title: 'Story de Bastidores',
        description: 'Mostrar o processo de criação nos bastidores do escritório.',
        type: 'story',
        status: 'scheduled',
        scheduledAt: '2026-03-10T09:00:00',
        hashtags: ['#bastidores', '#behindthescenes'],
        mediaUrls: [],
        accountId: 'a1',
        collectionIds: [],
        order: 1,
        createdAt: '2026-03-08T12:00:00',
        updatedAt: '2026-03-09T08:00:00',
    },
    {
        id: 'c3',
        title: 'Reel Dicas de Produtividade',
        description: '5 dicas rápidas para aumentar a produtividade no dia a dia.',
        type: 'reel',
        status: 'draft',
        scheduledAt: null,
        hashtags: ['#produtividade', '#dicas', '#reels'],
        mediaUrls: [],
        accountId: 'a1',
        collectionIds: [],
        order: 2,
        createdAt: '2026-03-07T15:00:00',
        updatedAt: '2026-03-08T10:00:00',
    },
    {
        id: 'c4',
        title: 'Carrossel Tendências 2026',
        description: 'As 10 principais tendências de marketing digital para 2026.',
        type: 'carousel',
        status: 'idea',
        scheduledAt: null,
        hashtags: ['#tendências', '#marketing', '#2026'],
        mediaUrls: [],
        accountId: null,
        collectionIds: [],
        order: 3,
        createdAt: '2026-03-06T09:00:00',
        updatedAt: '2026-03-06T09:00:00',
    },
    {
        id: 'c5',
        title: 'Post Depoimento do Cliente',
        description: 'Depoimento real de um cliente satisfeito com resultados mensuráveis.',
        type: 'post',
        status: 'published',
        scheduledAt: '2026-03-05T10:00:00',
        hashtags: ['#depoimento', '#cliente', '#resultados'],
        mediaUrls: [],
        accountId: 'a1',
        collectionIds: [],
        order: 4,
        createdAt: '2026-03-04T08:00:00',
        updatedAt: '2026-03-05T10:00:00',
    },
    {
        id: 'c6',
        title: 'Story Enquete: Qual Conteúdo Vocês Preferem?',
        description: 'Enquete interativa para engajar seguidores e entender preferências.',
        type: 'story',
        status: 'idea',
        scheduledAt: null,
        hashtags: ['#enquete', '#interação'],
        mediaUrls: [],
        accountId: 'a1',
        collectionIds: [],
        order: 5,
        createdAt: '2026-03-09T11:00:00',
        updatedAt: '2026-03-09T11:00:00',
    },
    {
        id: 'c7',
        title: 'Reel Tutorial Edição no Canva',
        description: 'Tutorial passo a passo de edição de imagens no Canva para iniciantes.',
        type: 'reel',
        status: 'approved',
        scheduledAt: '2026-03-12T16:00:00',
        hashtags: ['#tutorial', '#canva', '#design'],
        mediaUrls: [],
        accountId: 'a1',
        collectionIds: [],
        order: 6,
        createdAt: '2026-03-07T14:00:00',
        updatedAt: '2026-03-09T09:00:00',
    },
    {
        id: 'c8',
        title: 'Post Frase Motivacional Segunda',
        description: 'Post com frase motivacional para começar a semana com energia.',
        type: 'post',
        status: 'scheduled',
        scheduledAt: '2026-03-10T07:00:00',
        hashtags: ['#motivação', '#segunda', '#bomdia'],
        mediaUrls: [],
        accountId: 'a1',
        collectionIds: [],
        order: 7,
        createdAt: '2026-03-08T18:00:00',
        updatedAt: '2026-03-09T06:00:00',
    },
    {
        id: 'c9',
        title: 'Carrossel Case de Sucesso',
        description: 'Case detalhado de como ajudamos a marca X a crescer 300% em 6 meses.',
        type: 'carousel',
        status: 'draft',
        scheduledAt: null,
        hashtags: ['#casesucesso', '#crescimento', '#marketing'],
        mediaUrls: [],
        accountId: 'a1',
        collectionIds: [],
        order: 8,
        createdAt: '2026-03-05T16:00:00',
        updatedAt: '2026-03-08T12:00:00',
    },
    {
        id: 'c10',
        title: 'Story Countdown Evento',
        description: 'Countdown para o evento ao vivo de sexta-feira.',
        type: 'story',
        status: 'scheduled',
        scheduledAt: '2026-03-14T18:00:00',
        hashtags: ['#evento', '#aovivo', '#countdown'],
        mediaUrls: [],
        accountId: 'a1',
        collectionIds: [],
        order: 9,
        createdAt: '2026-03-09T10:00:00',
        updatedAt: '2026-03-09T10:00:00',
    },
];
